version: '2.6.1'

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    links:
      - mongo
    mongo:
      volumes:
        - ./data:/data/db
      ports:
        - '27018:27017'
