name: Build and deploy in Heroku

on:
  push:
    branches:
      - "*"
jobs:
  tests:
    name: run tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Run unit tests
        run: npm ci && npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3