name: Tests

on:
  push:
    branches:
      - "main"
      - "master"
      - "feat/workflows"
  pull_request:
    branches:
      - "main"
      - "master"
      - "tests"
jobs:
  Job1:
    name: run tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo DATABASE_URL=${{ secrets.JWT_SECRET }} >> .env
          echo DATABASE_URL=${{ secrets.CLOUDNARY_NAME }} >> .env
          echo DATABASE_URL=${{ secrets.API_CLOUDNARY_KEY }} >> .env
          echo DATABASE_URL=${{ secrets.API_CLOUDNARY_SECRET }} >> .env
          cat .env
      - name: Run npm commands
      - run: npm ci
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3