name: Run tests in devlopment branch

on:
  push:
    branches:
      - "dev"
jobs:
  tests:
    name: run tests (dev)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: setup envs
        run: |
          touch .env
          echo NODE_ENV=development >> .env
          cat .env
      - name: Run unit tests
        run: npm ci && npm test